### ISSUE TITLE
请大佬看看，我安装时卡在这里是什么原因？

### ISSUE THREAD

**Issue by qybust** [jcheunglin/HP-Elitebook-830-G5-Hackintosh#4]
大佬，我也是830G5，配置差不多，只是我的是8350u，照着您的设置，使用你的efi，总是卡在这一步，您知道为什么吗？
![IMG_20200324_185028](https://user-images.githubusercontent.com/17663480/77438843-49d6a000-6e21-11ea-9d89-53eada430cd8.jpg)

**Comment by jcheunglin** [comment]
Bios 设置里面选了没

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: qybust<mailto:notifications@github.com>
发送时间: 2020年3月24日 22:49
收件人: jcheunglin/HP-Elitebook-830-G5-Hackintosh<mailto:HP-Elitebook-830-G5-Hackintosh@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [jcheunglin/HP-Elitebook-830-G5-Hackintosh] 请大佬看看，我安装时卡在这里是什么原因？ (#4)


大佬，我也是830G5，配置差不多，只是我的是8350u，照着您的设置，使用你的efi，总是卡在这一步，您知道为什么吗？
[IMG_20200324_185028]<https://user-images.githubusercontent.com/17663480/77438843-49d6a000-6e21-11ea-9d89-53eada430cd8.jpg>

―

**Comment by qybust** [comment]
bios里设置了，包括关闭vtx&d，谢谢大佬的回答，找了能找到的830G5系列的efi安装很多次失败后实在丧气，已经把机子卖掉了😂

**Comment by jcheunglin** [comment]
@qybust 抱歉回复晚了，bios设置我下面贴了一个连接，是kinoute 850 g5的设置不知道你注意到没，那个里面有几个关键选项，其中有个wlan唤醒那个需要勾掉，我之前试验了一下，这个选项会导致比较明显的问题
